apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-spot-cluster
  region: us-east-1

vpc:
  subnets:
    public:
      us-east-1a:
        id: subnet-08c9f4e0084d2e626

managedNodeGroups:
  - name: spot
    instanceType: m5.large
    spot: true
    availabilityZones:
    - us-east-1a
    desiredCapacity: 3
    ssh:
      publicKeyName: roboshop.pub
